In [33]:
import numpy as np

In [34]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [36]:
np.ones([2,2], int)

array([[1, 1],
       [1, 1]])

In [37]:
np.ones([3,2], float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [38]:
X = np.array([[1,2,3], [4,5,6]], int)

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

In [39]:
np.full((4, 8), 10)

array([[10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10]])

In [40]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.random.randint(100, size=5)

array([16, 38, 46, 45, 82])

In [42]:
X = [1, 2, 3]
Y = np.array(X)
print(Y)

[1 2 3]


In [43]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
X = np.array(['A','B','C','D','E'])

X[-1]

'E'

In [45]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

In [46]:
X = [0, 10, -5, 40, -3]

X.sort()
print(X)

[-5, -3, 0, 10, 40]


In [47]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10, 7, 9])

mask = X > 5

print(X[mask])

[ 6 10  7  9]


In [48]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4, 10, 8, 7, 3])

print(X.sum())
print(X.mean())
print(X.std())
print(X.max())

71
5.461538461538462
2.468739467058648
10
